### ISSUE TITLE
Downloads of dependencies are hard-coded

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#1]
The [scripts/build_scripts/README.md](https://github.com/bio-phys/complexespp/blob/master/scripts/build_scripts/README.md) suggests that I may specify versions of the dependencies in [scripts/build_scripts/build.cfg](https://github.com/bio-phys/complexespp/blob/master/scripts/build_scripts/build.cfg). However, the downloads in [scripts/build_scripts/build_deps.sh](https://github.com/bio-phys/complexespp/blob/master/scripts/build_scripts/build_deps.sh) are actually hard coded.

Thus, if the user, e.g., changes

```
#BOOST="boost_1_60_0" 
BOOST="boost_1_71_0" 
```

in build_deps.sh

This script will not work anymore.
I suppose the best fix would be to clarify that the users need to take care of the dependencies themselves, if they want to use different versions.

**Comment by kain88-de** [comment]
does this explain your problem compiling the code?

**Comment by kain88-de** [comment]
Hm we should be remove the line to choose dependencies. Rather use as is.

**Comment by kain88-de** [comment]
hard coding is fine and we never mention that those should be changed.
