### ISSUE TITLE
Provide manual only as pdf?

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#14]
I understand that in the development stage, it made sense to include the manual in tex format. However, I have to say that it includes a lot of non-standard latex packages. Therefore, it is not very convenient for the users, since they will have to download a lot of extra packages eventually, before they can look up small details.
I would suggest to include the manual as pdf for an actual release of complexes.

**Comment by berenger-eu** [comment]
This has been fixed, right? As I see a manual.pdf file (in the manual directory).

**Comment by Clownshift** [comment]
> This has been fixed, right? As I see a manual.pdf file (in the manual directory).

Yes, you are right, it missed it before. It does exist as pdf in the repository. Should we keep both, tex and pdf in the repo?

**Comment by Clownshift** [comment]
I would suggest to put the .tex files for the manual in a separate, private repository?
Then the users are not bothered with it and for future adaptations, it is still under version control for the developers.
Do you think it makes sense?

**Comment by berenger-eu** [comment]
Yes I think that would be ok.

**Comment by kain88-de** [comment]
Please just keep it here. It does not hurt. Keeping Code and documentation aligned is already hard.  No need making it more difficult by making it private repo.

**Comment by berenger-eu** [comment]
Ok, maybe we can move the latex source in a sub directory to have the pdf more accessible?
