### ISSUE TITLE
Keep main, delete master branch?

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#16]
Currently, we have both: master branch and main branch.
Since 2020, github is working to replace the term master branch, with main branch (read about that [here](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) )

I believe that it is a little confusing currently to have both. I think we should decide for either of the two.
I suggest to use main instead of master. 

It is a little invasive for the current userbase, though, because they will not be able to pull from the master branch anymore, if they originally cloned the repository from the master branch.

**Comment by jkoefinger** [comment]
Good point. Let's ensure that the main branch is  and then delete the master branch.

**Comment by kain88-de** [comment]
Everything is main since last week. I thought I deleted master already.

**Comment by Clownshift** [comment]
Nope, master still exists. I will delete it now.
