### ISSUE TITLE
Issues with installation: when dependency exist globally and is build with out build helpers

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#2]
I tried to install complexes by first building the dependencies:
```
cd scripts/build_scripts
bash build_deps.sh
```
This seems to run as expected. If I try to continue with:
`bash build_dynamic.sh`
I get the following error message:
```
usr/bin/ld: CMakeFiles/complexes++_objects.dir/util/file.cpp.o: in function `_GLOBAL__sub_I__ZN4util14backUpIfExistsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
file.cpp:(.text.startup+0x9): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: file.cpp:(.text.startup+0xe): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: file.cpp:(.text.startup+0x17): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
```
I am trying to install the software on Ubuntu 20.04, with gcc 9.3.0 and cmake version 3.16.3
boost library: libboost1.71-dev:amd64

I noticed that make also tries to use boost1.71, even though boost1.60 was downloaded as a dependency. I googled a little, but I am still pretty lost... 
@kain88-de can you give me a hint?

**Comment by kain88-de** [comment]
Hm. Ubuntu 21.10 and a clean checkout work for me. Did you change any of the files?

**Comment by Clownshift** [comment]
I tried it on a different machine:
debian 9.13
gcc 6.3
cmake 3.17.2
boost 1.62-dev

There it works out of the box.

**Comment by kain88-de** [comment]
That is an old GCC version and old Debian version. The current Debian
stable is 11.x

**Comment by kain88-de** [comment]
my ubuntu installation is fairly new. No system boot dependencies are installed. That might interfere with your build. Difficult to say without direct access to the system.

**Comment by Clownshift** [comment]
For the time being I just work with a static build, so that I can continue the testing. However, I would still like to get to the bottom of this. @kain88-de Do you have a hunch what to look for?

**Comment by kain88-de** [comment]
Sorry no idea.

**Comment by kain88-de** [comment]
Might be a problem when we install a boost version from the dependencies. Which os is hte problematic machine running.

**Comment by kain88-de** [comment]
I could reproduce this on a new ubuntu 21.10 installation. Once boost is already installed on the system  our build system fails. @jkoefinger if someone from mpcdf could look at this would be nice, the original build scripts have been written by @reuterk.

**Comment by Clownshift** [comment]
I think the problem maybe fixed by specifying $BOOST_ROOT, since in build_dynamic this is referenced [in this line](https://github.com/bio-phys/complexespp/blob/99120466a08d2d5c4eb4f3aa2cd5b93371d3cd69/scripts/build_scripts/build_dynamic.sh#L63). I think for the MPCDF this was done by the module environment (I cannot check anymore though...)

Potentially, we could include something linke FindBoost.cmake, as it is mentioned [on stackoverflow](https://stackoverflow.com/questions/3016448/how-can-i-get-cmake-to-find-my-alternative-boost-installation).

**Comment by reuterk** [comment]
OK, to me the current situation looks as follows:

* The script 'build_deps.sh' does *not* build shared libraries at all, the lines/flags are commented out in the current master branch (for whatever reason).
* The script 'build_shared.sh' prefers shared objects and falls back to static libraries, if necessary.  On a system with newer Boost libraries (/usr/lib64/libboost*.so) locally installed, these may have priority which in turn may lead to the issues you're seeing on Ubuntu 21.10.
* The script 'build_static.sh' works correctly, picking up the static libs only.

Options to resolve the issue:

1)  Uncomment the lines related to the shared objects in 'build_deps.sh' and rebuild the libraries and then the application using 'build_dynamic.sh'.  This works, and an rpath is written into the executable pointing to the correct location.
2)  Use the static build (which may not work well for MPI builds).

**Comment by kain88-de** [comment]
Thank you for having a look at this. I'll try your suggestions. I cannot remember why I deactivated dynamic linking.

**Comment by kain88-de** [comment]
Building the dynamic does not help unfortunately. Once you install boost via the package manager it is currently game over. Setting boost_root does not help either. I'm not sure what the best way is to force cmake into using our boost dependency.

**Comment by kain88-de** [comment]
I'll just remove boost. One dependency less.

**Comment by reuterk** [comment]
Thanks, this sounds like a good option, if feasible. Until implemented we can use/recommend the static build.

In principle it *should* be possible to hack the use of the correct Boost installation into the CMAKE config, but given the plethora of platforms and configurations out there we'd probably never be able to cover all cases.

**Comment by kain88-de** [comment]
I got boost and libfmt either replaced or included as a sub project.
Yaml-cpp has the same compile issues. But I cannot easily add the sources
as a sub directory, yank-cpp also uses cmake. My current idea is to replace
it with rapidyaml, they support cmake sub directory.

**Comment by kain88-de** [comment]
build works without installing boost or libfmt. yaml is still an open questions though.

**Comment by kain88-de** [comment]
yaml is not pulled during the build process.
