### ISSUE TITLE
pair kernel test fails

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/complexespp#21]
[PAIRKERNELS.testFails](https://github.com/bio-phys/complexespp/blob/b86688b3f5281df8e23391ea25636e117c0d5532/complexes%2B%2B/test/unit-test/test_pairkernels.cpp#L330-L334) fails with a switch of arguments in the error message. The order of those is actually important, as we can define different interactions between A -> B and B -> A, if memory serves right. 

```
/home/max/code/complexespp/complexes++/test/unit-test/test_pairkernels.cpp:320: Failure
Value of: e.what()
  Actual: "PairKernelManager -- pair B / A has already been defined"
Expected: "PairKernelManager -- pair A / B has already been defined"
```

@berenger-eu  can you have a look at that?

I build everything locally on ubuntu 21.10 with the stock GCC compiler and libyaml-cpp-dev installed.

**Comment by berenger-eu** [comment]
@kain88-de it is fixed, no?

**Comment by kain88-de** [comment]
Not fixed

**Comment by berenger-eu** [comment]
Ok this is commented, I will have a look.
