### ISSUE TITLE
Cannot compile, because of strange fmt error

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#26]
This has been brought up previously, here #25

**Comment by Clownshift** [comment]
The error logs again:

https://github.com/bio-phys/complexespp/pull/25#issuecomment-1072514839

**Comment by Clownshift** [comment]
This is mentioned in the error-log:

`/home/berenger/Projects/complexespp/complexes++/ext/fmt-8.1.1/include/fmt/chrono.h:338:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)`

Might this be an issue with the compiler version?

**Comment by kain88-de** [comment]
I can check on the weekend. For now try deleting all precompiled dependencies and run the build scripts. Do not build the dependencies again. This requires that Libyans-cpp-dev is installed Ubuntu/Debian based os.

**Comment by berenger-eu** [comment]
So for me cmake generate this line to compile file.o, which fails:
`
cd /home/berenger/Projects/complexespp/complexes++/build/src && /usr/bin/c++  -I/home/berenger/Projects/complexespp/complexes++/build/ext/inastemp/Src -I/home/berenger/Projects/complexespp/complexes++/ext/inastemp/Src -I/home/berenger/Projects/complexespp/complexes++/build/src -isystem /home/berenger/Projects/complexespp/complexes++/src -isystem /home/berenger/Projects/complexespp/complexes++/build/ext/xdrfile-1.1.4/1.1.4/include -isystem /home/berenger/complexes-pp/dep/include -isystem /home/berenger/Projects/complexespp/complexes++/ext/CLI11 -isystem /home/berenger/Projects/complexespp/complexes++/ext/fmt-8.1.1/include -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Woverloaded-virtual -Wpointer-arith -Wcast-qual -Wconversion -Wold-style-cast -fopenmp -Werror  -mavx2 -march=native -mavx -march=native -msse4 -msse4.2 -march=native -msse4 -msse4.1 -march=native -mssse3 -march=native -msse3 -march=native -Wold-style-cast -O3 -DNDEBUG -ffast-math -march=native -std=c++17 -MD -MT src/CMakeFiles/complexes++_objects.dir/util/file.cpp.o -MF CMakeFiles/complexes++_objects.dir/util/file.cpp.o.d -o CMakeFiles/complexes++_objects.dir/util/file.cpp.o -c /home/berenger/Projects/complexespp/complexes++/src/util/file.cpp
`

But when I simply moved the -I for fmt at the beginning, it works....
`
cd /home/berenger/Projects/complexespp/complexes++/build/src && /usr/bin/c++  -isystem /home/berenger/Projects/complexespp/complexes++/ext/fmt-8.1.1/include -I/home/berenger/Projects/complexespp/complexes++/build/ext/inastemp/Src -I/home/berenger/Projects/complexespp/complexes++/ext/inastemp/Src -I/home/berenger/Projects/complexespp/complexes++/build/src -isystem /home/berenger/Projects/complexespp/complexes++/src -isystem /home/berenger/Projects/complexespp/complexes++/build/ext/xdrfile-1.1.4/1.1.4/include -isystem /home/berenger/complexes-pp/dep/include -isystem /home/berenger/Projects/complexespp/complexes++/ext/CLI11 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Woverloaded-virtual -Wpointer-arith -Wcast-qual -Wconversion -Wold-style-cast -fopenmp -Werror  -mavx2 -march=native -mavx -march=native -msse4 -msse4.2 -march=native -msse4 -msse4.1 -march=native -mssse3 -march=native -msse3 -march=native -Wold-style-cast -O3 -DNDEBUG -ffast-math -march=native -std=c++17 -MD -MT src/CMakeFiles/complexes++_objects.dir/util/file.cpp.o -MF CMakeFiles/complexes++_objects.dir/util/file.cpp.o.d -o CMakeFiles/complexes++_objects.dir/util/file.cpp.o -c /home/berenger/Projects/complexespp/complexes++/src/util/file.cpp
`

I do not know what to say :s

**Comment by berenger-eu** [comment]
Ok it seems that -isystem instead of -I is the problem, but I check again.

**Comment by berenger-eu** [comment]
Yes I confirm. But I have no idea why -isystem is used. I guess it comes from the cmake of fmt.

**Comment by berenger-eu** [comment]
If I remove "SYSTEM" in the inclusion of the headers, I have the google test that fails to compile :(
```
include_directories(SYSTEM
  ${CMAKE_CURRENT_SOURCE_DIR}/src
  ${XDRFILE_INCLUDE_DIR}
  ${yaml-cpp_INCLUDE_DIR}
  ext/CLI11
  # FMT should not need this according to docs
  ext/fmt-8.1.1/include
  )
```
But if I simply move the fmt dir first, that works... that is a little fragile, but well if that works for all of us I would keep it like this.

**Comment by kain88-de** [comment]
In your example compile command I still see `-isystem /home/berenger/complexes-pp/dep/include`. I assume this is the include for libyaml-cpp. This would happen with the build scripts. I assume that folder still includes sources for fmt 3.x, what we previously used. During the build now `/home/berenger/complexes-pp/dep/include` is searched for the fmt sources. That version of the library does not contain chrono.h. So you end up using `/home/berenger/Projects/complexespp/complexes++/ext/fmt-8.1.1/include/fmt/chrono.h` and all other includes from `/home/berenger/complexes-pp/dep/include`, those do not match. Not by moving the include to the left of the command line, you tell gcc to [prefer the left most folder](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html) and include matching header files for libfmt. So this looks like an artefact not cleaning up the build script helpers and having two versions of the same library "installed". 

Can you try to see if this still matters once the libfmt headers are removed from `/home/berenger/complexes-pp/dep/include`?

**Comment by berenger-eu** [comment]
Indeed I confirm that seems to solve the problem.
