### ISSUE TITLE
REMC tutorial does not run through

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#5]
I think there might be multiple problems. So far I identified the following:
If the REMC simulation was started multiple times, the log file is appended. However, the demux tool cannot handle appended log files, apparently.

I suppose this is an issue by itself, that needs to be solved. (Will create separate issues eventually...)

**Comment by Clownshift** [comment]
#6

**Comment by kain88-de** [comment]
duplicate of #6
