### ISSUE TITLE
backup log files on restart

### ISSUE THREAD

**Issue by Clownshift** [bio-phys/complexespp#6]
Complexes creates backups of already existing files and creates fresh files for most output. An exception are the complexes log files: These are continuously appended, run after run, if the user does not delete the current log file.
Unfortunately, demux apparently cannot handly appended log files.

To work around this issue I suppose to prepare a module that strips the last simulation run from an appended log file.
This solution is rather non invasive, because I do not touch the actual simulation engine at all. Neither do I need to change other pycomplexes modules, apart from demux and even that I only need to adapt slightly.

**Comment by kain88-de** [comment]
Normally we backup files and create new files. The  log file is the exception of this. It is created so early in the boot up process that it does not touch the backup machinery. The ideal solution is to backup the log files as well. 

[log helper](https://github.com/bio-phys/complexespp/blob/main/complexes%2B%2B/src/util/log.h)
[backup machinery](https://github.com/bio-phys/complexespp/blob/aab205959ccd6014e2cc8a85fb97315b050dc4fc/complexes%2B%2B/src/mc/simulation.cpp#L202)
